### PR TITLE
Fixed issue with local player disappearing if other player disconnect…

### PR DESCRIPTION
**Pull request by niekschoemaker**
…ed while in appartment

### CODE REVIEW

**Comment by niekschoemaker** [comment]
GetPlayerFromServerId() returns -1 when the serverID doesn't exist.
This caused players which disconnect inside their appartment to cause all players to not be able to see themselves untill the plugin gets reloaded. Adding a CloseInstance to playerDropped fixes this issue.

**Comment by ModatherM** [comment]
didn't work..

**Comment by Oreax** [comment]
I haven't had people become invisible when others Disconnect.
For me it's been:
Player A logs out from his apartment. (all is still good).
When Player A connects again, everyone on the server turns invisible, but him, until he exits his apartment. Then he becomes invisible like the rest.

@ModatherM Responding from the other post - I don't have the solution, I was just posting I think could be the issue, but I have not yet found a solution to it.

**Comment by ElPumpo** [comment]
@niekschoemaker can you confirm that this fixes #10 ?

**Comment by ModatherM** [comment]
@Oreax Well no problem, i have tried to make @niekschoemaker solution too but seems not working too, idk whats the problem..

**Comment by EGUltraTM** [comment]
@instance/server/main.lua:138: attempt to index a nil value (global 'instances')

i get this error when adding this:

the line is:
 if instances[_source] ~= nil then

**Comment by niekschoemaker** [comment]
I should probably add that I changed a few more things which fully fixed it which is a simple check for (NetworkIsPlayerActive and player > 0 ) on the client sided loops, that fully fixed it, I'll update the pull request with those changes

**Comment by EGUltraTM** [comment]
Yeah please add it would be awesome :)

**Comment by EGUltraTM** [comment]
> 
> 
> I should probably add that I changed a few more things which fully fixed it which is a simple check for (NetworkIsPlayerActive and player > 0 ) on the client sided loops, that fully fixed it, I'll update the pull request with those changes

Please push your changes would love it

**Comment by abu3beid** [comment]
can anyone confirm if this works or not?

**Comment by niekschoemaker** [comment]
> 
> 
> > I should probably add that I changed a few more things which fully fixed it which is a simple check for (NetworkIsPlayerActive and player > 0 ) on the client sided loops, that fully fixed it, I'll update the pull request with those changes
> 
> Please push your changes would love it

I pushed them just now, this should fix the issues, at least haven't had any reports of the issue in the last week or so. Also changed a for in pairs loop to a regular for loop, since those are a bit faster.

**Pull request closed without merging**
